# Generated by Django 4.1.7 on 2023-03-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="API_User",
        ),
    ]
